// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
// Try to load .env file, but don't fail if it doesn't exist (Docker case)
try {
  dotenv.config();
} catch (e) {
  // Ignore dotenv errors - environment variables may come from Docker
}
import { defineConfig } from "prisma/config";

const databaseUrl = process.env.DATABASE_URL || process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
